#!/usr/bin/env bash

# function opbash_signin() {
#     op list templates >>/dev/null 2>&1
#     if [[ $? -ne 0 ]]; then
#         eval $(op signin)
#     fi
# }

function opbash_get_names() {
    op item list
}

function opbash_get_entry() {
    passwd=$(op item get "$1" --reveal --fields password)
    echo "$passwd" | wl-copy
}

# opbash_signin
opname=$(opbash_get_names | fzf | awk '{print $1}')
opbash_get_entry "$opname"
