#!/usr/bin/env bash

winclass="$(xdotool search --class symbol)";
if [ -z "$winclass" ]; then
    feh --scale-down --auto-zoom --geometry 600x100 ~/keyboard/kbd75/symbol.png --class symbol --reload=0
else
    if [ ! -f /tmp/symbol ]; then
        touch /tmp/symbol && xdo hide "$winclass"
    elif [ -f /tmp/symbol ]; then
        rm /tmp/symbol && xdo show "$winclass"
    fi
fi

