#!/usr/bin/env bash

# $1 = user input from tmux command-prompt
user_input="$1"

# Capture the current pane
scroll_position=$(tmux display -p -F "#{scroll_position}")
pane_height=$(tmux display -p -F "#{pane_height}")
if [ -z "$scroll_position" ] || [ -z "$pane_height" ]; then
  tmux capture-pane -p >/tmp/buffer.log
else
  start_line="$((scroll_position))"
  end_line="$((scroll_position - pane_height))"
  echo $start_line >>/tmp/buffer.log.log
  echo $end_line >>/tmp/buffer.log.log

  tmux capture-pane -p \
    -S "-$start_line" \
    -E "-$end_line" \
    >/tmp/buffer.log
fi

RELEVANT_TRACE=$(grep -E '^[[:space:]]*(at|-> at)' /tmp/buffer.log | grep "$user_input" | head -n 1)
PAREN_CONTENT=$(echo "$RELEVANT_TRACE" | grep -oP '\(.*?\)' | tr -d '()')

# THIS hangs
echo "$PAREN_CONTENT" | wl-copy
tmux send -X copy-pipe-and-cancel "$(clipboard_copy_command)"

tmux display-message -d 5000 "Copied $PAREN_CONTENT"
