#!/usr/bin/env bash

# Use the first argument as the directory, default to $HOME/wiki if no argument is given
dir="${1:-$HOME/wiki}"

if [ ! -d "$dir" ]; then
    echo "Error: Directory '$dir' does not exist."
    exit 1
fi

tmux neww bash -c "
cd \"$dir\"

RELOAD='reload:rg --column --color=always --smart-case {q} || :'
OPENER='nvim {1} +{2}'

fzf --disabled --ansi --multi \
    --header 'Enter: open file | Ctrl-n: create file from current query | Ctrl-/ toggle preview' \
    --bind \"enter:become(\$OPENER)\" \
    --bind \"start:\$RELOAD\" \
    --bind \"change:\$RELOAD\" \
    --bind 'ctrl-/:toggle-preview' \
    --bind \"ctrl-n:execute(nvim {q}.md > /dev/tty)\" \
    --delimiter : \
    --preview 'if [ {2} -gt 0 ]; then bat --style=full --color=always --highlight-line {2} {1}; else bat --style=full --color=always {1}; fi' \
    --preview-window '~4,+{2}+4/3,<80(up)'
"
