general {
    gaps_in = 3
    gaps_out = 6
    border_size = 2
    col.active_border = rgba(7894abff)

    col.inactive_border = rgba(31324466)
    col.nogroup_border = 0xff89dceb
    col.nogroup_border_active = 0xfff9e2af
    resize_on_border = true
}

# cursor {
#     inactive_timeout = 5
#     hide_on_key_press = true
# }

# windowrulev2 = opacity 0.80, class:^(com.mitchellh.ghostty)$
decoration {
  rounding = 10
  active_opacity = 1.0
  blur {

enabled = true

size = 5

passes = 3

vibrancy = 0.1696

}

  shadow {
    enabled = true
    range = 8
    render_power = 3
    color = rgba(7894ab40)
    color_inactive = rgba(00000010)
  }

  dim_inactive = false
  dim_strength = 0.2
  inactive_opacity = 0.9
}


animations {
    enabled = true
       bezier = overshot,0.05,0.9,0.1,1.1

    animation = windows, 1, 7, overshot
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 100, default, loop
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default, slidefade 60%
    animation = specialWorkspace, 1, 6, default, slidefadevert 20%

}

layerrule = blur, notifications
layerrule = ignorealpha 0.2, notifications


