# vim:ft=tmux
# status
thm_bg="#1e1e2e"
thm_fg="#cdd6f4"
thm_cyan="#89dceb"
thm_black="#181825"
thm_gray="#313244"
thm_magenta="#B48EAD"
thm_pink="#f5c2e7"
thm_red="#f38ba8"
thm_green="#a6e3a1"
thm_yellow="#f9e2af"
thm_blue="#89b4fa"
thm_orange="#fab387"
thm_black4="#585b70"
primary="$COLOR_PRIMARY"
text="$COLOR_BACKGROUND"

set -g status-position top
set -g status 2
set -g status-format[1] "#[fg=$thm_gray]#{R:─,#{client_width}}"
set -g status-bg "default"
set -g status-justify "left"
set -g status-left-length 100
set -g status-right-length 100

# messages
set -g message-style fg="${thm_cyan}",bg="${thm_gray}",align="centre"
set -g message-command-style fg="${thm_cyan}",bg="${thm_gray}",align="centre"

set-window-option -g pane-active-border-style fg=$thm_cyan,bold
set-window-option -g pane-border-style fg=$thm_gray
set-window-option -g pane-border-indicators off
set-window-option -g pane-border-status top
set-window-option -g pane-border-format "#{?pane_active,#[fg=$thm_bg bg=$thm_cyan bold fill=$thm_cyan] ● ACTIVE · #P · #{pane_current_command} #[align=right]#{b:pane_current_path} ,#[fg=$thm_black4 bg=$thm_gray fill=$thm_gray] #P · #{pane_current_command} #[align=right]#{b:pane_current_path} }"

# windows
setw -g window-status-activity-style fg="${thm_fg}",none
setw -g window-status-separator ""
setw -g window-status-style fg="${thm_fg}",bg="default",none
set -g status-style bg=default,fg=white # transparent bg with neutral text

# --------=== Statusline
status_background="#{?client_prefix,$thm_red,$thm_cyan}"
session_text="#{?client_prefix,PREFIX,#S}"

session="#[fg=$status_background,bold] 󰄛 $session_text #[fg=$thm_fg,nobold]   "
set -g status-left "$session"
set -g status-right ""

# numbered windows
setw -g window-status-format "#[fg=$thm_black4]  #I  "
setw -g window-status-current-format "#[bg=$status_background,fg=$thm_bg,bold]  #I  #[bg=default,fg=$thm_fg,nobold]  "
