#! /bin/sh

rofi_cmd() {
    rofi -dmenu \
        -theme ~/.config/rofi/configs/power.rasi
}

chosen=$(printf "  \n  \n  \n 󰤄 " | rofi_cmd)

suspend_lock() {
    swayidle -w \
        timeout 1 'systemctl suspend' \
        resume 'killall -9 swayidle' \
        before-sleep 'swaylock -f -c 000000 -i ~/wallpapers/evening-sky.png'
}
lock() {
    if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
        swaylock --image ~/wallpapers/evening-sky.png
    else
        i3lock --image ~/wallpapers/evening-sky.png
    fi
}
case "$chosen" in
"  ") poweroff ;;
"  ") reboot ;;
"  ") lock ;;
" 󰤄 ")
    suspend_lock
    ;;
*) exit 1 ;;
esac
