#! /bin/sh

rofi_cmd() {
    rofi -dmenu \
        -theme ~/.config/rofi/configs/power.rasi
}

chosen=$(printf "  \n  \n  \n 󰤄 " | rofi_cmd)

lock() {
    i3lock --image ~/wallpapers/evening-sky.png
}
case "$chosen" in
"  ") poweroff ;;
"  ") reboot ;;
"  ") lock ;;
" 󰤄 ") systemctl suspend ;;
*) exit 1 ;;
esac
